[package]
name = "calendar-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "calendar-backend"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4.0"
env_logger = "0.10.0"
rusqlite = { version = "0.29.0", features = ["bundled"] }
actix-web = { version = "4.4.0", features = ["rustls-0_21"]}
rustls = "0.21.7"
rustls-pemfile = "1.0.3"
actix-cors = "0.6.4"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.33.0", features = ["macros"] }
secrecy = { version = "0.8" }
anyhow = "1"
thiserror = "1"
regex = "1.10.2"
argon2 = { version = "0.5.1", features = ["std"] }
rand = "0.8.4"
jsonwebtoken = "8.3.0"
