[package]
name = "calendar-backend"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
name = "calendar_backend_lib"

[[bin]]
path = "src/main.rs"
name = "calendar-backend"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4.22"
env_logger = "0.11.5"
rusqlite = { version = "0.32.1", features = ["bundled"] }
actix-web = { version = "4.9.0", features = ["rustls-0_23"]}
rustls = "0.23.12"
rustls-pemfile = "2.1.3"
actix-cors = "0.7.0"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread", "test-util"] }
secrecy = { version = "0.8" }
anyhow = "1"
thiserror = "1"
regex = "1.10.6"
argon2 = { version = "0.5.3", features = ["std"] }
rand = "0.8.4"
jsonwebtoken = "9.3.0"
chrono = "0.4.38"
chrono-tz = "0.9.0"
uuid = { version = "1.10.0", features = ["v4"] }
serial_test = "3.1.1"
