[package]
name = "calendar-backend"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
name = "calendar_backend_lib"

[[bin]]
path = "src/main.rs"
name = "calendar-backend"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4.21"
env_logger = "0.11.3"
rusqlite = { version = "0.31.0", features = ["bundled"] }
actix-web = { version = "4.5.1", features = ["rustls-0_22"]}
rustls = "0.22.2"
rustls-pemfile = "2.1.1"
actix-cors = "0.7.0"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread", "test-util"] }
secrecy = { version = "0.8" }
anyhow = "1"
thiserror = "1"
regex = "1.10.3"
argon2 = { version = "0.5.3", features = ["std"] }
rand = "0.8.4"
jsonwebtoken = "9.2.0"
chrono = "0.4.35"
chrono-tz = "0.8.6"
uuid = { version = "1.8.0", features = ["v4"] }
