[package]
name = "calendar-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "calendar-backend"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4.0"
env_logger = "0.11.0"
rusqlite = { version = "0.30.0", features = ["bundled"] }
actix-web = { version = "4.4.1", features = ["rustls-0_21"]}
rustls = "0.21.9"
rustls-pemfile = "1.0.4"
actix-cors = "0.7.0"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.35.1", features = ["macros"] }
secrecy = { version = "0.8" }
anyhow = "1"
thiserror = "1"
regex = "1.10.3"
argon2 = { version = "0.5.3", features = ["std"] }
rand = "0.8.4"
jsonwebtoken = "9.2.0"
chrono = "0.4.32"
chrono-tz = "0.8.5"
