apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: calendar-backend
  name: calendar-backend
  namespace: calendar-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calendar-backend
  template:
    metadata:
      labels:
        app: calendar-backend
    spec:
      containers:
      - image: ghcr.io/calendar-team/calendar-backend
        name: calendar-backend
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /calendar/db/
          name: calendar-backend-db
        env:
        - name: CALENDAR_IS_PROD_ENV
          value: "1"
        - name: CALENDAR_JWT_SIGNING_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-key
              key: jwt-key
        - name: CALENDAR_DB_PATH
          value: /calendar/db/database.db3
      - image: ghcr.io/calendar-team/sqlite-to-r2
        name: db-backup
        ports:
        - containerPort: 3333
          protocol: TCP
        volumeMounts:
        - mountPath: /calendar/db/
          name: calendar-backend-db
          readOnly: true
        env:
        - name: BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: db-backup
              key: bucket-name
        - name: ACCOUNT_ID
          valueFrom:
            secretKeyRef:
              name: db-backup
              key: account-id
        - name: ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: db-backup
              key: access-key-id
        - name: ACCESS_KEY_SECRET
          valueFrom:
            secretKeyRef:
              name: db-backup
              key: access-key-secret
        - name: DB_FILE_PATH
          value: /calendar/db/database.db3
      volumes:
      - persistentVolumeClaim:
          claimName: calendar-backend-db
        name: calendar-backend-db
      imagePullSecrets:
      - name: ghcr-secret

