apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calendar-backend-db
  namespace: calendar-backend
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi

