name: Deploy to EC2

on:
  push:
    branches: [ "deploy_to_ec2_on_push_on_master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Deploy to EC2
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i --delete"
        SOURCE: "target/"
        TARGET: "/home/ec2-user/calendar-backend"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        SCRIPT_BEFORE: killall calendar-backend
        SCRIPT_AFTER: |
          /home/ec2-user/calendar-backend/debug/calendar-backend &
          disown
