name: Deploy to EC2

on:
  push:
    branches: [ "make_cors_production_ready" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Deploy to EC2
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i --delete"
        SOURCE: "target/"
        TARGET: "/home/ec2-user/calendar-backend"
        EXCLUDE: "/debug/build, /debug/deps/, /debug/examples/, /debug/incremental/, /debug/.fingerprint/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        SCRIPT_AFTER: |
          sudo killall calendar-backend
          sudo RUST_LOG=debug CALENDAR_IS_PROD_ENV=1 /home/ec2-user/calendar-backend/debug/calendar-backend  > ./output.log 2>&1 &
          disown
